name: Deploy to Cloud run
on:  
  push:

env:
  SERVICE: ${{ github.event.repository.name }}
  IMAGE_NAME: us.gcr.io/jeraby-sup/juan/huella-carbono
  PORT: 80

jobs:
  deploy-cloudrun:
    runs-on: ubuntu-latest
    steps:

      - name: Setup Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.1
        with:
          project_id: jeraby-sup
          service_account_key: ${{ secrets.GOOGLE_CREDENTIAL }}
          export_default_credentials: true

      - name: Authorize docker push
        run: gcloud auth configure-docker

      - name: Build docker image
        env:
          DOCKER_BUILDKIT: 1
        run: |-
          docker build -t ${{ env.IMAGE_NAME }}:${{ github.sha }} .
          docker push ${{ env.IMAGE_NAME }}:${{ github.sha }}
      - name: Deploy to cloud run
        env:
          SERVICE: ${{ env.SERVICE }}
        uses: google-github-actions/deploy-cloudrun@v0.6.0
        with:
          service: ${{ env.SERVICE }}
          image: ${{ env.IMAGE_NAME }}:${{ github.sha }}
          region: us-central1
          flags: --cpu=1 --memory=512Mi --platform=managed --no-use-http2 --allow-unauthenticated --port ${{ env.PORT }}
      - name: Show output
        run: echo ${{ steps.deploy.outputs.url }}